blank_issues_enabled: false
contact_links:
  - name: ???
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    about: |
      - Never gonna give you up  
      - Never gonna let you down  
      - Never gonna run around and desert you  
      - Never gonna make you cry  
      - Never gonna say goodbye  
      - Never gonna tell a lie and hurt you
